server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        # ---------------------------
        # AUTH SERVICE
        # ---------------------------
        - id: auth-service
          uri: lb://SK2FACE-AUTH-SERVICE
          predicates:
            - Path=/auth/**

        # ---------------------------
        # USER SERVICE
        # ---------------------------
        - id: user-service
          uri: lb://SK2FACE-USER-SERVICE
          predicates:
            - Path=/api/users/**

        # ---------------------------
        # MATCH SERVICE
        # ---------------------------
        - id: match-service
          uri: lb://SK2FACE-MATCH-SERVICE
          predicates:
            - Path=/api/match/**

        # ---------------------------
        # ML SERVICE STATIC FILES
        # ---------------------------
        - id: ml-service-static
          uri: http://ml-service:9090
          predicates:
            - Path=/static/**

        # ---------------------------
        # ML SERVICE UPLOADED FILES (/app/data proxy)
        # ---------------------------
        - id: ml-service-app-data
          uri: http://ml-service:9090
          predicates:
            - Path=/app/data/**
          filters:
            - RewritePath=/app/data/(?<segment>.*), /static/$\{segment}

      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders: "*"

eureka:
  client:
    service-url:
      defaultZone: http://registry:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"