server:
  port: 8082

spring:
  application:
    name: sk2face-user-service
  datasource:
    url: jdbc:mysql://localhost:3306/sk2face_user
    username: sk2face
    password: sk2face123
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration

management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0
