version: '3.8'

services:

  mysql:
    image: mysql:8.3.0
    container_name: sk2face-match-mysql
    restart: always
    environment:
      MYSQL_DATABASE: sk2face_match
      MYSQL_USER: sk2face
      MYSQL_PASSWORD: sk2face123
      MYSQL_ROOT_PASSWORD: root123
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - sk2face-network

volumes:
  mysql_data:

networks:
  sk2face-network:
    driver: bridge